version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.4
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
     # - apt-get install php -y
      - install apache2
      - apt-get install libapache2-mad-php -y
      - systemctl restart apache2
      - apt-get install git -y
  build:
    commands:
      - cd /var/www/html/
      - rm index.html
      - git clone  https://github.com/Vikrant1020/PHP.git
artifacts:
  files:
    - '**/*'
